apiVersion: v1
kind: Pod
metadata:
  name: data-pod-brats
  labels:
    app: data-pod-brats
spec:
  nodeSelector:
    topology.kubernetes.io/region: us-west
    nautilus.io/linstor: "true"
  
  containers:
    - name: brats-processing
      image: gitlab-registry.nrp-nautilus.io/prp/jupyter-stack/prp
      
      env:
        - name: REPO_PATH
          value: /app/UNETR-BraTS-Synthesis
        - name: PYTHONPATH
          value: /app/UNETR-BraTS-Synthesis
        - name: PYTHONUNBUFFERED
          value: "1"
        - name: PYTHONIOENCODING
          value: "UTF-8"
      
      command: ["/bin/bash", "-c"]
      args:
        - |



          tail -f /dev/null
      
      volumeMounts:
        - name: workspace
          mountPath: /app
        - name: data2
          mountPath: /data2
        - name: data3
          mountPath: /data3
        - name: data4
          mountPath: /data4
        - name: data5
          mountPath: /data5
        - name: shm
          mountPath: /dev/shm
      
  
  volumes:
    - name: workspace
      emptyDir:
        sizeLimit: 50Gi
    - name: data2
      persistentVolumeClaim:
        claimName: brats2025-2
    - name: data3
      persistentVolumeClaim:
        claimName: brats2025-3
    - name: data4
      persistentVolumeClaim:
        claimName: brats2025-4
    - name: data5
      persistentVolumeClaim:
        claimName: brats2025-5
    - name: shm
      emptyDir:
        medium: Memory
        sizeLimit: 16Gi
  
  restartPolicy: Never