apiVersion: v1
kind: Pod
metadata:
  name: brats-seg-eval
spec:
  nodeSelector:
    #topology.kubernetes.io/region: us-west
    nautilus.io/linstor: "true"
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: nvidia.com/gpu.product
            operator: In
            values:
            - NVIDIA-A10
            - NVIDIA-GeForce-RTX-3090
            - NVIDIA-GeForce-RTX-4090
            - NVIDIA-TITAN-RTX
            - NVIDIA-RTX-A5000
            - Quadro-RTX-6000
            - Tesla-V100-SXM2-32GB
            - NVIDIA-A40
            - NVIDIA-L40
            - NVIDIA-RTX-A6000
            - Quadro-RTX-8000
  containers:
  - name: brats-seg
    image: brainles/brats24_adult_glioma_faking_it:latest
    command: ["/bin/bash", "-c"]
    args:
    - |
      apt-get update
      sudo apt-get install -y p7zip-full wget git

      7z x /data/ASNR-MICCAI-BraTS2023-GLI-MET-ValidationData.tar.gz
      7z x ASNR-MICCAI-BraTS2023-GLI-MET-ValidationData.tar
      
      # cp ASNR-MICCAI-BraTS2023-GLI-MET-ValidationData/BraTS-GLI-00001-000/*.nii.gz /mlcube_io0/BraTS-GLI-00000-000/

      # cd /mlcube_io0/BraTS-GLI-00000-000/
      # mv BraTS-GLI-00001-000-t1c.nii.gz BraTS-GLI-00000-000-t1c.nii.gz
      # mv BraTS-GLI-00001-000-t1n.nii.gz BraTS-GLI-00000-000-t1n.nii.gz
      # mv BraTS-GLI-00001-000-t2f.nii.gz BraTS-GLI-00000-000-t2f.nii.gz
      # mv BraTS-GLI-00001-000-t2w.nii.gz BraTS-GLI-00000-000-t2w.nii.gz

      # ls -la

      cd mlcube_project
      python3 mlcube.py infer --data_path=/mlcube_io0 --output_path=/mlcube_io2

      tail -f /dev/null
      
    resources:
      requests:
        memory: 24Gi
        cpu: "12"
        nvidia.com/gpu: "1"
      limits:
        memory: 32Gi
        cpu: "16"
        nvidia.com/gpu: "1"
   
    volumeMounts:
    - name: data
      mountPath: /data
    - name: input-data
      mountPath: /mlcube_io0
    - name: output-data
      mountPath: /mlcube_io2
  volumes:
  - name: data
    persistentVolumeClaim:
      claimName: brats2025-5
  - name: input-data
    emptyDir:
      sizeLimit: 10Gi
  - name: output-data
    emptyDir:
      sizeLimit: 5Gi
  restartPolicy: Never